### ISSUE TITLE
.!.

### ISSUE THREAD

**Issue by j4k0m** [0x00Jeff/injectors#1]
3andak dkhol crisis discord

**Comment by yezz123** [comment]
gharib amr Jeff

**Comment by 0x00Jeff** [comment]
hhhhhhhhhhhh f*ck off lmao, you ruined my first issue :man_facepalming: 

just lemme take ma break man  o ghatchofoni 7ta t3yaw dik sa3a, mab9a gd ma fat

**Comment by j4k0m** [comment]
xdddd
